/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HotelManagement.FrontDesk;

import UI.HotelManagement.FrontDesk.FrontDeskWorkAreaJPanel;
import Business.HotelEnterprise.HotelEnterprise;
import Business.Network.HotelNetwork;
import Business.Organization.AssaultOrganization;
import Business.Organization.HouseKeepingOrganization;
import Business.Organization.HotelOrganization;
import Business.Organization.TheftOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Complaints_Suggestions_Request;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author pulakantidikshithreddy
 */
public class FrontDeskComplaintJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FrontDeskComplaintJPanel
     */
    public String message1 = null;
    private JPanel userProcessContainer;
    private HotelEnterprise enterprise;
    private UserAccount userAccount;
    JTextField messageJTextField = new JTextField();
    HotelNetwork network;
    public FrontDeskComplaintJPanel(JPanel userProcessContainer, UserAccount userAccount, HotelEnterprise enterprise,HotelNetwork network) {
        initComponents();
        this.network=network;
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
        populateComboBox();
    }
    Complaints_Suggestions_Request request = new Complaints_Suggestions_Request();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtMessage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DepartmentCombobox = new javax.swing.JComboBox<>();
        btnSendComplaint = new javax.swing.JButton();

        jLabel1.setText("Front Desk Complaints Area");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Message :");

        TxtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMessageActionPerformed(evt);
            }
        });

        jLabel3.setText("Department :");

        DepartmentCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DepartmentCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentComboboxActionPerformed(evt);
            }
        });

        btnSendComplaint.setText("Send Complaint");
        btnSendComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendComplaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(264, 264, 264))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSendComplaint)
                    .addComponent(DepartmentCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(TxtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DepartmentCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnSendComplaint)
                .addContainerGap(285, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DepartmentComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartmentComboboxActionPerformed

    private void btnSendComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendComplaintActionPerformed
        // TODO add your handling code here:
        String message = TxtMessage.getText();
        System.out.println("sendComplaintActionPerformed 'messageJTextField' " + message);
        System.out.println("sendComplaintActionPerformed 'messageJTextField' " + TxtMessage.getText());
        
    if(message.isEmpty())
        
        {
            
            JOptionPane.showMessageDialog(null,"Message field should not be empty");
        }
    else
    {       
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");

        HotelOrganization org = null;
        HotelOrganization.Type sel = (HotelOrganization.Type) DepartmentCombobox.getSelectedItem();
        if(sel.equals(HotelOrganization.Type.Assault))
        {
            for (HotelEnterprise enterprise: network.getEnterpriseDirectory().getHotelEnterpriseList())
            {
                  for(HotelOrganization organization:enterprise.getOrganizationDirectory().getHotelOrganizationList())
                  {
                if (organization instanceof AssaultOrganization){
                    org = organization;
                    break;
                } }
            }
            if (org!=null){
                org.getStatusQueue().getStatusRequestList().add(request);
                userAccount.getStatusQueue().getStatusRequestList().add(request);
            }
            JOptionPane.showMessageDialog(null,"Your Assault complaint has been sent");

        }
        
        else if(sel.equals(HotelOrganization.Type.Theft))
        {
             for (HotelEnterprise enterprise: network.getEnterpriseDirectory().getHotelEnterpriseList())
            {
                  for(HotelOrganization organization:enterprise.getOrganizationDirectory().getHotelOrganizationList())
                  {
                if (organization instanceof TheftOrganization){
                    org = organization;
                    break;
                } 
            }
            }
            if (org!=null){
                org.getStatusQueue().getStatusRequestList().add(request);
                userAccount.getStatusQueue().getStatusRequestList().add(request);
            }
        JOptionPane.showMessageDialog(null,"Your Theft complaint has been sent");

        }
        
            

                }
    }//GEN-LAST:event_btnSendComplaintActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FrontDeskWorkAreaJPanel FDWA = (FrontDeskWorkAreaJPanel) component;
        FDWA.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void TxtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMessageActionPerformed
        // TODO add your handling code here:
        if(TxtMessage.getText()!= null)
        {
        message1 = TxtMessage.getText();
        
        }
        else JOptionPane.showMessageDialog(null,"Message field should not be empty");
    }//GEN-LAST:event_TxtMessageActionPerformed

    private void populateComboBox() {
        
        DepartmentCombobox.removeAllItems();
        DepartmentCombobox.addItem(HotelOrganization.Type.Assault);
        DepartmentCombobox.addItem(HotelOrganization.Type.Theft);
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DepartmentCombobox;
    private javax.swing.JTextField TxtMessage;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendComplaint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
