/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HotelManagement.FrontDesk;

import Business.HotelEnterprise.HotelEnterprise;
import Business.Network.HotelNetwork;
import Business.Organization.AssaultOrganization;
import Business.Organization.HouseKeepingOrganization;
import Business.Organization.HotelOrganization;
import Business.Organization.TheftOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmergencyRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pulakantidikshithreddy
 */
public class FrontDeskEmergencyRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FrontDeskEmergencyRequestJPanel
     */
    public String message1 = null;
    private JPanel userProcessContainer;
    private HotelEnterprise enterprise;
    private UserAccount userAccount; 
    private HotelNetwork network;
    public FrontDeskEmergencyRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, HotelEnterprise enterprise,HotelNetwork network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.network=network;
        populateComboBox();
    }
    
    EmergencyRequest  erequest = new EmergencyRequest();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        locationlbl = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        locationtxtfield = new javax.swing.JTextField();
        btnsendemergency = new javax.swing.JButton();

        jLabel1.setText("Front Desk Emergency Requests");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Emergency Type :");

        locationlbl.setText("Location :");

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        btnsendemergency.setText("Send Emergency Request");
        btnsendemergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendemergencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(backJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(282, 282, 282))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(locationlbl))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsendemergency)
                    .addComponent(locationtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backJButton))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationlbl)
                    .addComponent(locationtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnsendemergency)
                .addContainerGap(270, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        FrontDeskWorkAreaJPanel FDWA = (FrontDeskWorkAreaJPanel) component;
        FDWA.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnsendemergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendemergencyActionPerformed
        // TODO add your handling code here:
        String location = locationtxtfield.getText();
        erequest.setLocation(location);
        erequest.setEmergencytype((HotelOrganization.Type) combo.getSelectedItem());
        erequest.setEmail(userAccount.getEmail());
         HotelOrganization org = null;
         HotelOrganization.Type sel = (HotelOrganization.Type) combo.getSelectedItem();
      if(location.isEmpty())
      {
       
            JOptionPane.showMessageDialog(null,"Location field should not be empty");     
    }
        
        else
        {
            
            
            if(sel.equals(HotelOrganization.Type.Theft))
        {   
        for (HotelEnterprise enterprise: network.getEnterpriseDirectory().getHotelEnterpriseList())
            {
                  for(HotelOrganization organization:enterprise.getOrganizationDirectory().getHotelOrganizationList())
                  {
            if (organization instanceof TheftOrganization){
                org = organization;
                break;
            } 
                  }
        }
        if (org!=null){
            org.getStatusQueue().getStatusRequestList().add(erequest);
            userAccount.getStatusQueue().getStatusRequestList().add(erequest);
        }
        }
          else if(sel.equals(HotelOrganization.Type.Assault))
        {
        
        for (HotelEnterprise enterprise: network.getEnterpriseDirectory().getHotelEnterpriseList())
            {
                  for(HotelOrganization organization:enterprise.getOrganizationDirectory().getHotelOrganizationList())
                  {
            if (organization instanceof AssaultOrganization){
                org = organization;
                break;
            } }
        }
        
        if (org!=null){
            org.getStatusQueue().getStatusRequestList().add(erequest);
            userAccount.getStatusQueue().getStatusRequestList().add(erequest);
        }
        }
        
          JOptionPane.showMessageDialog(null,"Your emergency request has been sent! An officer will notify you shortly");
        
            
        }
    }                                                

    private void locationtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        
        if(locationtxtfield.getText()!=""){
        message1 = locationtxtfield.getText();
        System.out.println("sendComplaintActionPerformed 'messageJTextField' " + message1);
        }
        else JOptionPane.showMessageDialog(null,"Location field should not be empty");
        
    }//GEN-LAST:event_btnsendemergencyActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed
private void populateComboBox() {
        
         combo.removeAllItems();
        combo.addItem(HotelOrganization.Type.Theft.toString());
        combo.addItem(HotelOrganization.Type.Assault.toString());
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnsendemergency;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel locationlbl;
    private javax.swing.JTextField locationtxtfield;
    // End of variables declaration//GEN-END:variables
}
