/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Services.Restaurants;

import Business.HotelEnterprise.HotelEnterprise;
import Business.Network.HotelNetwork;
import Business.Organization.AssaultOrganization;
import Business.Organization.RestaurantsOrganization;
import Business.Organization.HotelManagerOrganization;
import Business.Organization.HouseKeepingOrganization;
import Business.Organization.HotelOrganization;
import Business.Organization.TheftOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmergencyRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pulakantidikshithreddy
 */
public class RestaurantsEmergencyRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RestaurantsEmergencyRequestJPanel
     */
    public String message1 = null;
    private JPanel userProcessContainer;
    private HotelEnterprise enterprise;
    private UserAccount userAccount; 
    private HotelNetwork network;
    public RestaurantsEmergencyRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, HotelEnterprise enterprise,HotelNetwork network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.network=network;
     populateComboBox();
    }

    EmergencyRequest  erequest = new EmergencyRequest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        locationlbl = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        locationfield = new javax.swing.JTextField();
        btnSendEmergency = new javax.swing.JButton();

        jLabel1.setText("Security Emergency Requests");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Emergency Type :");

        locationlbl.setText("Location:");

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        locationfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationfieldActionPerformed(evt);
            }
        });

        btnSendEmergency.setText("Send Emergency");
        btnSendEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEmergencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnBack)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(locationlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSendEmergency))))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationlbl)
                    .addComponent(locationfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnSendEmergency)
                .addContainerGap(321, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RestaurantsWorkAreaJPanel RWA = (RestaurantsWorkAreaJPanel) component;
        RWA.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void locationfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationfieldActionPerformed
        // TODO add your handling code here:
        if(locationfiield.getText()!=""){
        message1 = locationfiield.getText();
        
        }
        else JOptionPane.showMessageDialog(null,"Location field is empty");
    }//GEN-LAST:event_locationfieldActionPerformed

    private void btnSendEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmergencyActionPerformed
        // TODO add your handling code here:
String location = locationfiield.getText();
        erequest.setLocation(location);
        erequest.setEmergencytype((HotelOrganization.Type) combo.getSelectedItem());
        erequest.setEmail(userAccount.getEmail());
         HotelOrganization org = null;
         HotelOrganization.Type sel = (HotelOrganization.Type) combo.getSelectedItem();
      if(location.isEmpty())
      {
        
            JOptionPane.showMessageDialog(null,"Location field is empty");     
    }
        
        else
        {
            
            
            if(sel.equals(HotelOrganization.Type.Theft))
        {   
        for (HotelEnterprise enterprise: network.getEnterpriseDirectory().getHotelEnterpriseList())
            {
                  for(HotelOrganization organization:enterprise.getOrganizationDirectory().getHotelOrganizationList())
                  {
            if (organization instanceof TheftOrganization){
                org = organization;
                break;
            } 
                  }
        }
        if (org!=null){
            org.getStatusQueue().getStatusRequestList().add(erequest);
            userAccount.getStatusQueue().getStatusRequestList().add(erequest);
        }
        }
          else if(sel.equals(HotelOrganization.Type.Assault))
        {
        
        for (HotelEnterprise enterprise: network.getEnterpriseDirectory().getHotelEnterpriseList())
            {
                  for(HotelOrganization organization:enterprise.getOrganizationDirectory().getHotelOrganizationList())
                  {
            if (organization instanceof AssaultOrganization){
                org = organization;
                break;
            } }
        }
         if (org!=null){
            org.getStatusQueue().getStatusRequestList().add(erequest);
            userAccount.getStatusQueue().getStatusRequestList().add(erequest);
        }
        }
        
          JOptionPane.showMessageDialog(null,"Your emergency request has been sent! An officer will notify you shortly");
        
        }
    }//GEN-LAST:event_btnSendEmergencyActionPerformed

    private void populateComboBox() {
        
         combo.removeAllItems();
        combo.addItem(HotelOrganization.Type.Theft);
        combo.addItem(HotelOrganization.Type.Assault);
       
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendEmergency;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField locationfield;
    private javax.swing.JLabel locationlbl;
    // End of variables declaration//GEN-END:variables
}



