/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.HotelManagement.HotelAdmin;

import Business.HotelEnterprise.HotelEnterprise;
import Business.Network.HotelNetwork;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Giridhar
 */
public class HotelAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HotelAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    HotelNetwork network;
    HotelEnterprise enterprise;
    
    public HotelAdminWorkAreaJPanel(JPanel userProcessContainer, HotelEnterprise enterprise, HotelNetwork network) {
        initComponents();
        this.network=network;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        lblEnterprise.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEnterpriseTitle = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        btnMngOrg = new javax.swing.JButton();
        btnMngEmp = new javax.swing.JButton();
        btnMngUsers = new javax.swing.JButton();

        lblTitle.setText("Hotel Management Enterprises Work Area");

        lblEnterpriseTitle.setText("Enterprise :");

        btnMngOrg.setText("Manage Organizations");
        btnMngOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngOrgActionPerformed(evt);
            }
        });

        btnMngEmp.setText("Manage Employees");
        btnMngEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngEmpActionPerformed(evt);
            }
        });

        btnMngUsers.setText("Manage Users");
        btnMngUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(lblEnterpriseTitle)
                        .addGap(18, 18, 18)
                        .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMngOrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMngEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMngUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 221, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblTitle)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnterpriseTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEnterprise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnMngOrg)
                .addGap(18, 18, 18)
                .addComponent(btnMngEmp)
                .addGap(18, 18, 18)
                .addComponent(btnMngUsers)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngEmpActionPerformed
        // TODO add your handling code here:
        ManageHotelEmployeeJPanel manageEmployeesJPanel = new ManageHotelEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeesJPanel", manageEmployeesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngEmpActionPerformed

    private void btnMngOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngOrgActionPerformed
        // TODO add your handling code here:
        ManageHotelOrganizationJPanel manageOrganizationsJPanel = new ManageHotelOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageOrganizationsJPanel", manageOrganizationsJPanel );
        CardLayout layout  = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngOrgActionPerformed

    private void btnMngUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngUsersActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel ManageUsersJPanel = new ManageUserAccountJPanel(userProcessContainer, enterprise,network);
        userProcessContainer.add("ManageUsersJPanel", ManageUsersJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngUsersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngEmp;
    private javax.swing.JButton btnMngOrg;
    private javax.swing.JButton btnMngUsers;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblEnterpriseTitle;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
