/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SignUp;

import Business.EcoSystem;
import UI.Security.Assault.AssaultWorkAreaJPanel;
import Validations.Validate;
import Validations.ValidateMail;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Giridhar
 */
public class AuthenticationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AuthenticationJPanel
     */
    Random rand = new Random();
    int n = rand.nextInt(10000);
    JPanel container;
    EcoSystem sys;
    public AuthenticationJPanel(JPanel container,EcoSystem sys) {
        initComponents();
        this.container=container;
        this.sys=sys;
         jLabel2.setVisible(false);
            txtAuth.setVisible(false);
            btnAuth.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSendMail = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAuth = new javax.swing.JTextField();
        btnAuth = new javax.swing.JButton();

        jLabel1.setText("Enter your email id for the verification ");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnSendMail.setText("Send Mail");
        btnSendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMailActionPerformed(evt);
            }
        });

        jLabel2.setText("Please enter the four digit code that has been sent to your email entered above");

        txtAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthActionPerformed(evt);
            }
        });

        btnAuth.setText("Authentication");
        btnAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSendMail)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAuth)
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtAuth, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSendMail)
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(txtAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnAuth)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthActionPerformed

    private void btnSendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMailActionPerformed
        // TODO add your handling code here:
        String emailID = null;
        if(txtEmail.getText()!=null)
            {
                if(Validate.validateEmail(txtEmail.getText()))
                {
                    emailID = txtEmail.getText();
                    System.out.println("email .. "+ emailID);
                    System.out.println("After If Statement .. ");
                    
                

         try {
             ValidateMail validateMail = new ValidateMail();
             try {
                 
             System.out.println("Inside If Statement .. ");
             validateMail.preparetoSendEmail("This is Subject", "This is Verification code : " + n, emailID);

             } catch (AddressException ex) {
                 Logger.getLogger(AuthenticationJPanel.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
                 Logger.getLogger(AuthenticationJPanel.class.getName()).log(Level.SEVERE, null, ex);
             }
              
            JOptionPane.showMessageDialog(this,"Mail has been sent");
            jLabel2.setVisible(true);
            txtAuth.setVisible(true);
            btnAuth.setVisible(true);
        } catch (MessagingException ex) {
            Logger.getLogger(AssaultWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Mail has not  been sent");
        }
         
                }     
                
            else {
            JOptionPane.showMessageDialog(null,"Please enter valid email id");
             System.out.println("Inside else Statement .. ");
            }
         
        }
        else {
            JOptionPane.showMessageDialog(null,"Please enter email id");
             System.out.println("Inside else Statement .. ");
            }
    }//GEN-LAST:event_btnSendMailActionPerformed

    private void btnAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthActionPerformed
        // TODO add your handling code here:
        Integer num = n; 
    
    
        if(num.equals(n))
        {
        
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("SignUpJPanel", new SignUpJPanel(container, sys,emailtxtfield.getText()));
        layout.next(container);
        
        }
        else
        {
        
          JOptionPane.showMessageDialog(null,"Authentication failed");
        
        }
    }//GEN-LAST:event_btnAuthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuth;
    private javax.swing.JButton btnSendMail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAuth;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
