/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SignUp;

import Business.EcoSystem;
import Business.HotelEmployee.HotelEmployee;
import Business.HotelEnterprise.HotelEnterprise;
import Business.Network.HotelNetwork;
import Business.Organization.HotelOrganization;
import Business.Role.Role;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Validations.Validate;

/**
 *
 * @author Giridhar
 */
public class SignupJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignupJPanel
     */
    JPanel Component;
    EcoSystem sys;
    String email;
    public SignupJPanel(JPanel Component,EcoSystem sys,String email) {
        initComponents();
        this.Component=Component;
        this.sys=sys;
        this.email=email;  
        PopNetworkCombo();
        emailtextfield.setText(email);
    }
    public void PopNetworkCombo()
           
    { 
        if(sys.getNetworkList().size()>0)
    {
          combonetwork.removeAllItems();
       for(HotelNetwork net: sys.getNetworkList())
       {
             
           combonetwork.addItem(net);
       }
       comboenterprise.setEnabled(true);
    }
    else 
    {
        JOptionPane.showMessageDialog(null,"No network available ");
     }
    }
    
    public void PopEnterpriseCombo(HotelNetwork network)
    {        
       comboenterprise.removeAllItems();
             //Network network = (Network) combonetwork.getSelectedItem();
         
           if(network.getEnterpriseDirectory().getHotelEnterpriseList().size()>0)
           {
               
               
                for(HotelEnterprise en: network.getEnterpriseDirectory().getHotelEnterpriseList())
                {
                     comboenterprise.addItem(en);
                }
  
          
           }
           
           else
           {
                combo_organization.setEnabled(false);
                comborole.setEnabled(false);
                JOptionPane.showMessageDialog(null,"Sorry !No enterprise available for this network");
           
               
           }
    }
    public void PopOrganizationCombo(HotelEnterprise ent)
    { 
        
         combo_organization.removeAllItems();
        
          combo_organization.setEnabled(true);
                  
             if (ent.getOrganizationDirectory().getHotelOrganizationList().size() > 0) {
                for (HotelOrganization organization : ent.getOrganizationDirectory().getHotelOrganizationList()) {
                    combo_organization.addItem(organization);
                }
            }
             else
             {
             
                  comborole.setEnabled(false);
                 JOptionPane.showMessageDialog(null,"Sorry !No organization available for this network");
             
             }
           
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combonetwork = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        comboenterprise = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        combo_organization = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        comborole = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passwordtxtfield = new javax.swing.JTextField();
        usernametxtfield = new javax.swing.JTextField();
        emailtextfield = new javax.swing.JTextField();
        emptxtfield = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Sign Up Form");

        jLabel2.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel2.setText("Network");

        combonetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combonetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combonetworkActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel3.setText("Enterprise");

        comboenterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboenterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboenterpriseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel4.setText("Organization");

        combo_organization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_organization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_organizationActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel9.setText("Role");

        comborole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel8.setText("Name");

        jLabel5.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel5.setText("Email ID");

        jLabel6.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel6.setText("UserName");

        jLabel7.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        jLabel7.setText("Password");

        passwordtxtfield.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N

        usernametxtfield.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N

        emailtextfield.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N
        emailtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtextfieldActionPerformed(evt);
            }
        });

        emptxtfield.setFont(new java.awt.Font("Optima", 0, 14)); // NOI18N

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addGap(48, 48, 48)
                                .addComponent(combonetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3)
                                .addGap(40, 40, 40)
                                .addComponent(comboenterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(46, 46, 46)
                                .addComponent(combo_organization, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel9)
                                .addGap(44, 44, 44)
                                .addComponent(comborole, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel8)
                                .addGap(7, 7, 7)
                                .addComponent(emptxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8)
                                .addComponent(emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(6, 6, 6)
                                .addComponent(usernametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel7)
                                .addGap(2, 2, 2)
                                .addComponent(passwordtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(btnSignUp)))
                .addContainerGap(564, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(combonetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3))
                            .addComponent(comboenterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4))
                            .addComponent(combo_organization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel9))
                            .addComponent(comborole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel8))
                            .addComponent(emptxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addComponent(emailtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addComponent(usernametxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addComponent(passwordtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47)
                .addComponent(btnSignUp)
                .addContainerGap(389, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combonetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combonetworkActionPerformed
        // TODO add your handling code here:
        HotelNetwork network = (HotelNetwork) combonetwork.getSelectedItem();
        if (network != null){
            PopEnterpriseCombo(network);

        }

    }//GEN-LAST:event_combonetworkActionPerformed

    private void comboenterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboenterpriseActionPerformed
        // TODO add your handling code here:
        HotelEnterprise  ent = (HotelEnterprise) comboenterprise.getSelectedItem();
        if (ent != null){
            PopOrganizationCombo(ent);

        }

    }//GEN-LAST:event_comboenterpriseActionPerformed

    private void combo_organizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_organizationActionPerformed
        // TODO add your handling code here:
        HotelOrganization org = (HotelOrganization) combo_organization.getSelectedItem();
        if (org != null){
            PopRoleCombo(org);

        }

    }//GEN-LAST:event_combo_organizationActionPerformed

    private void emailtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtextfieldActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        HotelNetwork network = (HotelNetwork) combonetwork.getSelectedItem();
        HotelEnterprise enterprise = (HotelEnterprise) comboenterprise.getSelectedItem();
        HotelOrganization organization = (HotelOrganization)combo_organization.getSelectedItem();
        Role role = (Role) comborole.getSelectedItem();
        
        for(HotelNetwork net : sys.getNetworkList() )
        {
            if(net.equals(network))
            {
                for(HotelEnterprise ent : net.getEnterpriseDirectory().getHotelEnterpriseList())
                {
                    if(ent.equals(enterprise))
                    {
                         for(HotelOrganization org: ent.getOrganizationDirectory().getHotelOrganizationList())
                         {
                                  
                             if(org.equals(organization))
                             { 
                                 if(emptxtfield.getText()!=null)
                                 { HotelEmployee emp= new HotelEmployee();
                                    emp.setName(emptxtfield.getText());
                                  
                                 if(emailtextfield.getText()!=null)
                                 {
                                        if(Validate.validateEmail(emailtextfield.getText()))
                                        {
                                             if(usernametxtfield.getText()!=null)
                                             {  
                                                 if(!EcoSystem.checkIfUsernameIsUnique(usernametxtfield.getText(),net))
                                                 {
                                                     
                                                     JOptionPane.showMessageDialog(null, usernametxtfield.getText() + " " + "is already taken please enter new username");
                                                     return;
                                                 }
                                                   if(passwordtxtfield.getText()!=null)
                                                   {
                                                       if (!Validate.validatePassword(passwordtxtfield.getText())) {
                                JOptionPane.showMessageDialog(null, "Password should Contain \n"
                                        + "       - At least one digit\n"
                                        + "       - At least one lower case letter\n"
                                        + "       - At least one upper case letter\n"
                                        + "       - At least one special character(!@#$%^&+=~|?)\n"
                                        + "       - no whitespace allowed in the entire string\n"
                                        + "       - at least eight characters");
                                passwordtxtfield.setText("");
                                return;
                            }organization.getUserAccountDirectory().createUserAccount(usernametxtfield.getText(), passwordtxtfield.getText(),emailtextfield.getText() ,emp, role);
                                                                   JOptionPane.showMessageDialog(null, "Account created succesfull");
                                                                     usernametxtfield.setText("");
                                                                        passwordtxtfield.setText("");
                                                                        emailtextfield.setText("");
                                                                        emptxtfield.setText("");
                                                                        
                                                                        
                                                        
                                                        
                                                   }
                                                   else
                                                   {
                                                      JOptionPane.showMessageDialog(null,"Please enter password");
                                                   
                                                   }
                                             }
                                             
                                             else
                                             {
                                                
                                                 JOptionPane.showMessageDialog(null,"Please enter username");
                                             
                                             }
                                        
                                        }
                                     else
                                        {
                                             JOptionPane.showMessageDialog(null,"Please enter valid email id");
                                        }
                                 }
                                 else
                                 {
                                      
                                     JOptionPane.showMessageDialog(null,"Please enter name");
                                     
                                 }
                                 }
                                 else
                                 {
                                      JOptionPane.showMessageDialog(null,"Please enter email id");
                                 }
                                      
                             
                             }
                         
                         }
                         
                    }
                
                
                }
               
            }
        
        
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    
    
    public void PopRoleCombo(HotelOrganization org)
    { 
        
            comborole.removeAllItems();
             comborole.setEnabled(true);
     
             
                  
             if (org.getSupportedRole().size()>0) {
                for (Role role : org.getSupportedRole()) {
                    comborole.addItem(role);
                }
            }
           
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JComboBox combo_organization;
    private javax.swing.JComboBox comboenterprise;
    private javax.swing.JComboBox combonetwork;
    private javax.swing.JComboBox comborole;
    private javax.swing.JTextField emailtextfield;
    private javax.swing.JTextField emptxtfield;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField passwordtxtfield;
    private javax.swing.JTextField usernametxtfield;
    // End of variables declaration//GEN-END:variables
}
